import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import {
  Bell, MessageSquare, TrendingUp, Shield, Calendar, Save,
  Zap, BarChart3, RefreshCw, Brain, Volume2, VolumeX, Smartphone, Info,
} from "lucide-react";
import { toast } from "sonner";

// ─── REAL-TIME NOTIFICATION TYPES ──────────────────────────────────
const REALTIME_TYPES = [
  {
    title: "Real-Time Alerts (WebSocket)",
    icon: <Zap className="w-4 h-4" />,
    desc: "Live push notifications delivered instantly via WebSocket",
    items: [
      { key: "rt_model_complete", label: "Model completions", desc: "When an analytical model finishes running", badge: "Model" },
      { key: "rt_propagation", label: "Propagation events", desc: "When data changes propagate across your financial twin", badge: "Propagation" },
      { key: "rt_coaching", label: "Coaching messages", desc: "Behavioral coaching nudges and insights", badge: "Coaching" },
      { key: "rt_system", label: "System alerts", desc: "Platform status, maintenance, and security alerts", badge: "System" },
      { key: "rt_compliance", label: "Compliance alerts", desc: "Compliance review results and flagged items", badge: "Compliance" },
      { key: "rt_insight", label: "AI insights", desc: "Proactive financial insights generated by AI", badge: "Insight" },
    ],
  },
];

// ─── DELIVERY METHOD CONTROLS ──────────────────────────────────────
const DELIVERY_METHODS = [
  { key: "dm_toast", label: "Toast popups", desc: "Show toast notifications for high-priority alerts", icon: <Bell className="w-4 h-4" /> },
  { key: "dm_sound", label: "Sound alerts", desc: "Play a sound when notifications arrive", icon: <Volume2 className="w-4 h-4" /> },
  { key: "dm_badge", label: "Badge counter", desc: "Show unread count on the notification bell", icon: <Smartphone className="w-4 h-4" /> },
];

// ─── EXISTING NOTIFICATION GROUPS ──────────────────────────────────
const NOTIFICATION_GROUPS = [
  {
    title: "Chat & AI",
    icon: <MessageSquare className="w-4 h-4" />,
    items: [
      { key: "chatMentions", label: "Chat mentions", desc: "When someone mentions you in a conversation" },
      { key: "aiInsights", label: "AI-generated insights", desc: "Proactive insights about your finances or clients" },
      { key: "studyReminders", label: "Study reminders", desc: "Reminders to continue learning sessions" },
    ],
  },
  {
    title: "Financial",
    icon: <TrendingUp className="w-4 h-4" />,
    items: [
      { key: "marketAlerts", label: "Market alerts", desc: "Significant market movements relevant to your portfolio" },
      { key: "goalProgress", label: "Goal milestones", desc: "When you reach financial goal milestones" },
      { key: "complianceAlerts", label: "Compliance alerts", desc: "Compliance review results and flagged items" },
    ],
  },
  {
    title: "Professional",
    icon: <Calendar className="w-4 h-4" />,
    items: [
      { key: "clientActivity", label: "Client activity", desc: "When clients complete suitability or upload documents" },
      { key: "meetingReminders", label: "Meeting reminders", desc: "Upcoming meeting briefs and follow-up reminders" },
      { key: "teamUpdates", label: "Team updates", desc: "Team member activity and performance summaries" },
    ],
  },
  {
    title: "System",
    icon: <Shield className="w-4 h-4" />,
    items: [
      { key: "securityAlerts", label: "Security alerts", desc: "Login from new device, password changes" },
      { key: "productUpdates", label: "Product updates", desc: "New features and platform improvements" },
    ],
  },
];

export default function NotificationsTab() {
  const [prefs, setPrefs] = useState<Record<string, boolean>>(() => {
    const saved = localStorage.getItem("wb_notification_prefs");
    if (saved) return JSON.parse(saved);
    // Default all to true
    const defaults: Record<string, boolean> = {};
    NOTIFICATION_GROUPS.forEach(g => g.items.forEach(i => { defaults[i.key] = true; }));
    REALTIME_TYPES.forEach(g => g.items.forEach(i => { defaults[i.key] = true; }));
    DELIVERY_METHODS.forEach(m => { defaults[m.key] = m.key !== "dm_sound"; }); // sound off by default
    return defaults;
  });

  const toggle = (key: string) => {
    setPrefs(p => ({ ...p, [key]: !p[key] }));
  };

  const save = () => {
    localStorage.setItem("wb_notification_prefs", JSON.stringify(prefs));
    toast.success("Notification preferences saved");
  };

  const enabledCount = Object.values(prefs).filter(Boolean).length;
  const totalCount = Object.keys(prefs).length;

  return (
    <div className="max-w-2xl space-y-6">
      <div>
        <h2 className="text-lg font-semibold mb-1">Notifications</h2>
        <p className="text-sm text-muted-foreground">
          Choose which notifications you receive and how they're delivered. {enabledCount}/{totalCount} enabled.
        </p>
      </div>

      {/* In-App Only Notice */}
      <div className="flex items-start gap-3 rounded-lg border border-accent/30 bg-accent/5 p-4">
        <Info className="w-5 h-5 text-accent mt-0.5 shrink-0" />
        <div>
          <p className="text-sm font-medium">In-App Notifications Only</p>
          <p className="text-xs text-muted-foreground mt-1">
            All notifications are delivered exclusively within the platform. Stewardly does not send any external emails, SMS, or push notifications. Your inbox stays clean.
          </p>
        </div>
      </div>

      {/* Delivery Methods */}
      <Card className="border-accent/20">
        <CardHeader className="pb-3">
          <CardTitle className="text-sm flex items-center gap-2">
            <Zap className="w-4 h-4 text-accent" /> Delivery Methods
          </CardTitle>
          <CardDescription className="text-xs">Control how in-app notifications are displayed</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {DELIVERY_METHODS.map(method => (
            <div key={method.key} className="flex items-center justify-between gap-4">
              <div className="flex items-center gap-3 min-w-0">
                <span className="text-muted-foreground">{method.icon}</span>
                <div>
                  <Label className="text-sm font-medium">{method.label}</Label>
                  <p className="text-[10px] text-muted-foreground">{method.desc}</p>
                </div>
              </div>
              <Switch checked={!!prefs[method.key]} onCheckedChange={() => toggle(method.key)} />
            </div>
          ))}
        </CardContent>
      </Card>

      {/* Real-Time Notification Types */}
      {REALTIME_TYPES.map(group => (
        <Card key={group.title} className="border-accent/20">
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <span className="text-accent">{group.icon}</span> {group.title}
            </CardTitle>
            <CardDescription className="text-xs">{group.desc}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {group.items.map(item => (
              <div key={item.key} className="flex items-center justify-between gap-4">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <Label className="text-sm font-medium">{item.label}</Label>
                    <Badge variant="outline" className="text-[9px] px-1.5 py-0">{item.badge}</Badge>
                  </div>
                  <p className="text-[10px] text-muted-foreground">{item.desc}</p>
                </div>
                <Switch checked={!!prefs[item.key]} onCheckedChange={() => toggle(item.key)} />
              </div>
            ))}
          </CardContent>
        </Card>
      ))}

      <Separator />

      {/* Standard Notification Groups */}
      {NOTIFICATION_GROUPS.map(group => (
        <Card key={group.title}>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm flex items-center gap-2">
              <span className="text-accent">{group.icon}</span> {group.title}
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {group.items.map(item => (
              <div key={item.key} className="flex items-center justify-between gap-4">
                <div className="min-w-0">
                  <Label className="text-sm font-medium">{item.label}</Label>
                  <p className="text-[10px] text-muted-foreground">{item.desc}</p>
                </div>
                <Switch checked={!!prefs[item.key]} onCheckedChange={() => toggle(item.key)} />
              </div>
            ))}
          </CardContent>
        </Card>
      ))}

      <Button onClick={save} className="gap-2">
        <Save className="w-4 h-4" /> Save Preferences
      </Button>
    </div>
  );
}
