-- Migration: Create Part G (Agentic Execution) tables
-- Tables: gate_reviews, agent_instances, agent_actions, insurance_quotes,
--         insurance_applications, advisory_executions, estate_documents,
--         premium_finance_cases, carrier_connections

CREATE TABLE IF NOT EXISTS `gate_reviews` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `actionId` VARCHAR(255) NOT NULL,
  `actionType` VARCHAR(100) NOT NULL,
  `complianceTier` INT NOT NULL DEFAULT 1,
  `classificationRationale` TEXT,
  `reviewerId` INT,
  `reviewerLicenseNumber` VARCHAR(100),
  `reviewerLicenseState` VARCHAR(10),
  `reviewerLicenseExpiry` BIGINT,
  `decision` ENUM('pending', 'approved', 'modified', 'rejected', 'escalated') DEFAULT 'pending',
  `modificationDetails` TEXT,
  `complianceNotes` TEXT,
  `decisionTimestamp` BIGINT,
  `archiveRef` VARCHAR(255),
  `workflowType` VARCHAR(100),
  `clientId` INT,
  `professionalId` INT,
  `firmId` INT,
  `slaDeadline` BIGINT,
  `escalatedTo` INT,
  `createdAt` BIGINT NOT NULL,
  INDEX `idx_gate_reviews_action_id` (`actionId`),
  INDEX `idx_gate_reviews_reviewer_id` (`reviewerId`),
  INDEX `idx_gate_reviews_client_id` (`clientId`),
  INDEX `idx_gate_reviews_professional_id` (`professionalId`),
  INDEX `idx_gate_reviews_firm_id` (`firmId`)
);

CREATE TABLE IF NOT EXISTS `agent_instances` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `userId` INT NOT NULL,
  `firmId` INT,
  `workflowType` VARCHAR(100) NOT NULL,
  `deploymentMode` ENUM('local', 'cloud', 'hybrid') DEFAULT 'local',
  `instanceStatus` ENUM('spawning', 'active', 'paused', 'terminated', 'error') DEFAULT 'spawning',
  `configJson` JSON,
  `budget_limit_usd` DECIMAL(10, 2),
  `runtimeLimitMinutes` INT DEFAULT 60,
  `totalActions` INT DEFAULT 0,
  `total_cost_usd` DECIMAL(10, 2) DEFAULT 0,
  `spawnedAt` BIGINT NOT NULL,
  `terminatedAt` BIGINT,
  INDEX `idx_agent_instances_user_id` (`userId`),
  INDEX `idx_agent_instances_firm_id` (`firmId`)
);

CREATE TABLE IF NOT EXISTS `agent_actions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `agentInstanceId` INT NOT NULL,
  `actionType` VARCHAR(100) NOT NULL,
  `targetSystem` VARCHAR(255),
  `targetUrl` TEXT,
  `dataAccessedSummary` TEXT,
  `dataModifiedSummary` TEXT,
  `screenshotHash` VARCHAR(255),
  `complianceTier` INT DEFAULT 1,
  `gate_triggered` BOOLEAN DEFAULT FALSE,
  `gateResult` VARCHAR(50),
  `durationMs` INT,
  `errorMessage` TEXT,
  `createdAt` BIGINT NOT NULL,
  INDEX `idx_agent_actions_agent_instance_id` (`agentInstanceId`)
);

CREATE TABLE IF NOT EXISTS `insurance_quotes` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clientId` INT NOT NULL,
  `professionalId` INT,
  `quoteRunId` VARCHAR(255) NOT NULL,
  `carrierName` VARCHAR(255) NOT NULL,
  `productType` VARCHAR(100) NOT NULL,
  `productName` VARCHAR(255),
  `premiumMonthly` DECIMAL(12, 2),
  `premiumAnnual` DECIMAL(12, 2),
  `deathBenefit` DECIMAL(15, 2),
  `cashValueYr10` DECIMAL(15, 2),
  `cashValueYr20` DECIMAL(15, 2),
  `ridersJson` JSON,
  `uwClassEstimated` VARCHAR(100),
  `amBestRating` VARCHAR(10),
  `quoteDate` BIGINT NOT NULL,
  `source` ENUM('api', 'browser', 'manual') DEFAULT 'manual',
  `status` ENUM('illustrative', 'reviewed', 'selected', 'expired') DEFAULT 'illustrative',
  `comparisonNotes` TEXT,
  INDEX `idx_insurance_quotes_client_id` (`clientId`),
  INDEX `idx_insurance_quotes_professional_id` (`professionalId`),
  INDEX `idx_insurance_quotes_quote_run_id` (`quoteRunId`)
);

CREATE TABLE IF NOT EXISTS `insurance_applications` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clientId` INT NOT NULL,
  `professionalId` INT,
  `carrierName` VARCHAR(255) NOT NULL,
  `productName` VARCHAR(255),
  `applicationDataJson` JSON,
  `preliminaryUwAssessment` TEXT,
  `compliancePreflightJson` JSON,
  `gateStatus` ENUM('draft', 'pending_review', 'approved', 'submitted', 'issued', 'declined', 'counter_offer') DEFAULT 'draft',
  `gateReviewId` INT,
  `reviewerId` INT,
  `reviewerLicense` VARCHAR(100),
  `reviewedAt` BIGINT,
  `submittedAt` BIGINT,
  `carrierStatus` VARCHAR(100),
  `carrierRefNumber` VARCHAR(255),
  `pendingRequirementsJson` JSON,
  `policyNumber` VARCHAR(255),
  `issuedAt` BIGINT,
  `createdAt` BIGINT NOT NULL,
  `updatedAt` BIGINT NOT NULL,
  INDEX `idx_insurance_applications_client_id` (`clientId`),
  INDEX `idx_insurance_applications_professional_id` (`professionalId`),
  INDEX `idx_insurance_applications_gate_review_id` (`gateReviewId`),
  INDEX `idx_insurance_applications_reviewer_id` (`reviewerId`)
);

CREATE TABLE IF NOT EXISTS `advisory_executions` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clientId` INT NOT NULL,
  `professionalId` INT NOT NULL,
  `executionType` ENUM('account_open', 'rebalance', 'harvest', 'transfer', 'trade', 'rollover') NOT NULL,
  `executionDataJson` JSON,
  `tax_impact_estimate` DECIMAL(12, 2),
  `gateStatus` ENUM('draft', 'pending_review', 'approved', 'executing', 'completed', 'failed') DEFAULT 'draft',
  `gateReviewId` INT,
  `reviewerId` INT,
  `approvedAt` BIGINT,
  `executedAt` BIGINT,
  `custodianConfirmation` VARCHAR(255),
  `postExecutionAuditJson` JSON,
  `createdAt` BIGINT NOT NULL,
  INDEX `idx_advisory_executions_client_id` (`clientId`),
  INDEX `idx_advisory_executions_professional_id` (`professionalId`),
  INDEX `idx_advisory_executions_gate_review_id` (`gateReviewId`),
  INDEX `idx_advisory_executions_reviewer_id` (`reviewerId`)
);

CREATE TABLE IF NOT EXISTS `estate_documents` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clientId` INT NOT NULL,
  `documentType` ENUM('trust', 'will', 'poa_financial', 'poa_healthcare', 'directive', 'beneficiary_audit') NOT NULL,
  `draftVersion` INT DEFAULT 1,
  `draftContentUrl` TEXT,
  `draftContentHash` VARCHAR(255),
  `complexityLevel` ENUM('simple', 'standard', 'complex') DEFAULT 'standard',
  `reviewPath` ENUM('self_help', 'attorney_review') DEFAULT 'attorney_review',
  `attorneyId` INT,
  `attorneyStatus` ENUM('pending', 'reviewing', 'approved', 'revision_requested') DEFAULT 'pending',
  `stateJurisdiction` VARCHAR(10),
  `finalized` BOOLEAN DEFAULT FALSE,
  `executedDate` BIGINT,
  `archiveRef` VARCHAR(255),
  `createdAt` BIGINT NOT NULL,
  `updatedAt` BIGINT NOT NULL,
  INDEX `idx_estate_documents_client_id` (`clientId`),
  INDEX `idx_estate_documents_attorney_id` (`attorneyId`)
);

CREATE TABLE IF NOT EXISTS `premium_finance_cases` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `clientId` INT NOT NULL,
  `professionalId` INT NOT NULL,
  `insurancePolicyRef` VARCHAR(255),
  `financedPremiumAnnual` DECIMAL(15, 2),
  `loanAmount` DECIMAL(15, 2),
  `lenderName` VARCHAR(255),
  `interestRate` DECIMAL(5, 3),
  `termYears` INT,
  `collateralType` VARCHAR(100),
  `collateralValue` DECIMAL(15, 2),
  `structureJson` JSON,
  `stressTestJson` JSON,
  `gateStatus` ENUM('modeling', 'pending_review', 'approved', 'applied', 'funded', 'monitoring', 'closed') DEFAULT 'modeling',
  `gateReviewId` INT,
  `status` ENUM('modeling', 'applied', 'funded', 'monitoring', 'closed') DEFAULT 'modeling',
  `monitoringAlertsJson` JSON,
  `createdAt` BIGINT NOT NULL,
  `updatedAt` BIGINT NOT NULL,
  INDEX `idx_premium_finance_cases_client_id` (`clientId`),
  INDEX `idx_premium_finance_cases_professional_id` (`professionalId`),
  INDEX `idx_premium_finance_cases_gate_review_id` (`gateReviewId`)
);

CREATE TABLE IF NOT EXISTS `carrier_connections` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `firmId` INT NOT NULL,
  `carrierName` VARCHAR(255) NOT NULL,
  `connectionType` ENUM('api', 'browser') DEFAULT 'browser',
  `apiEndpoint` VARCHAR(500),
  `credentialsVaultRef` VARCHAR(255),
  `supportedOperationsJson` JSON,
  `stateAppointmentsJson` JSON,
  `lastVerified` BIGINT,
  `active` BOOLEAN DEFAULT TRUE,
  `createdAt` BIGINT NOT NULL,
  INDEX `idx_carrier_connections_firm_id` (`firmId`)
);
