/**
 * pfrPdfGenerator.ts — Generate branded PFR PDF documents using PDFKit.
 * Produces professional client-facing Personal Financial Review documents
 * with proper typography, section formatting, and compliance disclosures.
 */
import PDFDocument from "pdfkit";

// ─── COLORS ────────────────────────────────────────────────────────
const C = {
  primary: [30, 64, 120] as [number, number, number],
  accent: [59, 130, 246] as [number, number, number],
  text: [30, 30, 40] as [number, number, number],
  muted: [120, 120, 140] as [number, number, number],
  bg: [248, 249, 252] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  divider: [220, 225, 235] as [number, number, number],
};

interface PFRPdfInput {
  clientName: string;
  advisorName: string;
  firmName: string;
  generatedAt: number;
  /** Markdown or plain text content from the PFR generator */
  content: string;
  sections?: Array<{ title: string; content: string }>;
}

/**
 * Generate a PDF buffer from PFR content.
 */
export async function generatePFRPdf(input: PFRPdfInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "letter",
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
        info: {
          Title: `Personal Financial Review — ${input.clientName}`,
          Author: input.advisorName,
          Creator: input.firmName,
        },
      });

      const chunks: Buffer[] = [];
      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
      const date = new Date(input.generatedAt).toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric",
      });

      // ─── HEADER ──────────────────────────────────────────────────
      doc.fontSize(24).fillColor(C.primary).text("Personal Financial Review", { align: "center" });
      doc.moveDown(0.3);
      doc.fontSize(14).fillColor(C.muted).text(`Prepared for ${input.clientName}`, { align: "center" });
      doc.moveDown(0.2);
      doc.fontSize(10).fillColor(C.muted).text(
        `Prepared by ${input.advisorName} | ${input.firmName}`,
        { align: "center" }
      );
      doc.fontSize(10).text(date, { align: "center" });
      doc.moveDown(0.5);

      // Divider line
      const lineY = doc.y;
      doc.moveTo(doc.page.margins.left, lineY)
        .lineTo(doc.page.width - doc.page.margins.right, lineY)
        .strokeColor(C.primary)
        .lineWidth(2)
        .stroke();
      doc.moveDown(1);

      // ─── CONTENT ─────────────────────────────────────────────────
      if (input.sections && input.sections.length > 0) {
        for (const section of input.sections) {
          renderSection(doc, section.title, section.content, pageWidth);
        }
      } else if (input.content) {
        // Parse markdown-style content into sections
        const parsed = parseMarkdownSections(input.content);
        for (const section of parsed) {
          renderSection(doc, section.title, section.content, pageWidth);
        }
      }

      // ─── DISCLAIMER ──────────────────────────────────────────────
      doc.moveDown(1);
      const disclaimerY = doc.y;
      doc.moveTo(doc.page.margins.left, disclaimerY)
        .lineTo(doc.page.width - doc.page.margins.right, disclaimerY)
        .strokeColor(C.divider)
        .lineWidth(0.5)
        .stroke();
      doc.moveDown(0.5);

      doc.fontSize(8).fillColor(C.muted).text(
        "Important Disclosure: This Personal Financial Review is prepared for informational purposes only " +
        "and does not constitute investment advice, tax advice, or a recommendation to purchase any financial " +
        "product. All projections and analyses are based on information provided and assumptions that may change. " +
        "Past performance does not guarantee future results. Please consult with qualified professionals before " +
        "making financial decisions.",
        { align: "left", lineGap: 2 }
      );
      doc.moveDown(0.3);
      doc.fontSize(8).text(
        "Securities and insurance products are not deposits, are not FDIC insured, are not insured by any " +
        "federal government agency, are not guaranteed by the firm, and may lose value.",
        { align: "left", lineGap: 2 }
      );

      // ─── FOOTER ──────────────────────────────────────────────────
      doc.moveDown(1);
      doc.fontSize(8).fillColor(C.muted).text(
        `Generated by ${input.firmName} | Confidential`,
        { align: "center" }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function renderSection(doc: PDFKit.PDFDocument, title: string, content: string, _pageWidth: number) {
  // Check if we need a new page (if less than 100pt remaining)
  if (doc.y > doc.page.height - doc.page.margins.bottom - 100) {
    doc.addPage();
  }

  // Section title
  doc.fontSize(16).fillColor(C.primary).text(title);
  doc.moveDown(0.2);

  // Light divider under title
  const lineY = doc.y;
  doc.moveTo(doc.page.margins.left, lineY)
    .lineTo(doc.page.width - doc.page.margins.right, lineY)
    .strokeColor(C.divider)
    .lineWidth(0.5)
    .stroke();
  doc.moveDown(0.4);

  // Content — handle bullet points and paragraphs
  const lines = content.split("\n");
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) {
      doc.moveDown(0.3);
      continue;
    }

    // Bullet points
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ") || trimmed.startsWith("• ")) {
      const bulletText = trimmed.replace(/^[-*•]\s+/, "");
      doc.fontSize(10).fillColor(C.text);
      const bulletX = doc.page.margins.left + 12;
      doc.text("•", doc.page.margins.left, doc.y, { continued: false });
      doc.text(bulletText, bulletX, doc.y - doc.currentLineHeight(), {
        width: doc.page.width - doc.page.margins.right - bulletX,
        lineGap: 2,
      });
      doc.moveDown(0.1);
      continue;
    }

    // Sub-headings (### or ##)
    if (trimmed.startsWith("###")) {
      doc.moveDown(0.3);
      doc.fontSize(12).fillColor(C.accent).text(trimmed.replace(/^#+\s*/, ""));
      doc.moveDown(0.2);
      continue;
    }
    if (trimmed.startsWith("##")) {
      doc.moveDown(0.3);
      doc.fontSize(14).fillColor(C.primary).text(trimmed.replace(/^#+\s*/, ""));
      doc.moveDown(0.2);
      continue;
    }

    // Bold text handling
    const boldParts = trimmed.split(/\*\*(.+?)\*\*/g);
    if (boldParts.length > 1) {
      doc.fontSize(10).fillColor(C.text);
      for (let i = 0; i < boldParts.length; i++) {
        if (i % 2 === 1) {
          // Bold part
          doc.font("Helvetica-Bold").text(boldParts[i], { continued: i < boldParts.length - 1 });
        } else if (boldParts[i]) {
          doc.font("Helvetica").text(boldParts[i], { continued: i < boldParts.length - 1 });
        }
      }
      doc.font("Helvetica");
      doc.moveDown(0.2);
      continue;
    }

    // Regular paragraph
    doc.fontSize(10).fillColor(C.text).text(trimmed, { lineGap: 2 });
    doc.moveDown(0.2);
  }

  doc.moveDown(0.5);
}

function parseMarkdownSections(content: string): Array<{ title: string; content: string }> {
  const sections: Array<{ title: string; content: string }> = [];
  const lines = content.split("\n");
  let currentTitle = "Overview";
  let currentContent: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    // Top-level section header
    if (trimmed.startsWith("# ") && !trimmed.startsWith("## ")) {
      if (currentContent.length > 0) {
        sections.push({ title: currentTitle, content: currentContent.join("\n") });
      }
      currentTitle = trimmed.replace(/^#\s+/, "");
      currentContent = [];
      continue;
    }
    if (trimmed.startsWith("## ") && !trimmed.startsWith("### ")) {
      if (currentContent.length > 0) {
        sections.push({ title: currentTitle, content: currentContent.join("\n") });
      }
      currentTitle = trimmed.replace(/^##\s+/, "");
      currentContent = [];
      continue;
    }
    currentContent.push(line);
  }
  if (currentContent.length > 0) {
    sections.push({ title: currentTitle, content: currentContent.join("\n") });
  }

  return sections;
}
