/**
 * Dashboard — post-login landing page (UI/UX Pass 84).
 *
 * Before this page existed, authenticated users went directly to `/chat`,
 * which meant: (1) there was no unified view of their activity across
 * the platform, (2) proactive insights generated by the AI engine had
 * no prominent UI surface, (3) guests and first-time users had no map
 * of what the platform could do.
 *
 * This page renders at `/dashboard` (NOT `/` — Landing.tsx stays as
 * the public marketing page, and `/chat` stays as the conversation
 * interface). Post-sign-in redirects now target `/dashboard` instead
 * of `/chat` so new users see the activity hub first. Anyone who
 * prefers Chat-first can bookmark `/chat` directly.
 *
 * The page is composed of four progressively-disclosed sections:
 *   1. Welcome header    — name + role badge + compact activity stats
 *   2. Quick actions row — role-gated FeatureCards matching the Hub
 *                          architecture from STEWARDLY_COMPREHENSIVE_GUIDE §5
 *   3. Recent activity   — last 3 conversations + top proactive insights
 *   4. Feature spotlight — for `undiscovered` features. Currently static;
 *                          later passes can wire it to user_feature_proficiency.
 *
 * Data flow: every query is against an EXISTING tRPC procedure. No
 * new backend was introduced for this page.
 *   - trpc.auth.me                          → role + display name
 *   - trpc.conversations.list                → recent conversations
 *   - trpc.insights.list                     → proactive insights
 *   - trpc.insights.stats                    → insight counts by status
 *   - trpc.learning.mastery.summary          → mastery % + streak
 *
 * Graceful degradation: every query handles loading + error states.
 * If any backend is unavailable, the affected tile shows a skeleton
 * and the rest of the page still renders.
 */

import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import AppShell from "@/components/AppShell";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import {
  MessageSquare,
  Brain,
  Calculator,
  GraduationCap,
  Users,
  Sparkles,
  ArrowRight,
  Activity,
  TrendingUp,
  Loader2,
  type LucideIcon,
} from "lucide-react";

// ─── Helpers ────────────────────────────────────────────────────────────────

function timeAgo(input: Date | string | number | null | undefined): string {
  if (!input) return "—";
  const t = typeof input === "number" ? input : new Date(input).getTime();
  if (!Number.isFinite(t)) return "—";
  const diff = Date.now() - t;
  const mins = Math.round(diff / 60_000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.round(hrs / 24);
  return `${days}d ago`;
}

function greeting(name: string | undefined): string {
  const hr = new Date().getHours();
  const who = name ? `, ${name.split(" ")[0]}` : "";
  if (hr < 12) return `Good morning${who}`;
  if (hr < 18) return `Good afternoon${who}`;
  return `Good evening${who}`;
}

// ─── Quick action cards ─────────────────────────────────────────────────────
//
// Each card maps to a primary Hub from STEWARDLY_COMPREHENSIVE_GUIDE §5.
// The CTA verb + description follow the emba_modules reference pattern
// ("Launch this" → "Do this thing"). Cards are role-gated so advisors
// see Advisory + Lead Pipeline, admins see everything.

interface QuickAction {
  title: string;
  description: string;
  cta: string;
  href: string;
  icon: LucideIcon;
  accent: string;
  minRole: "user" | "advisor" | "manager" | "admin";
}

const QUICK_ACTIONS: QuickAction[] = [
  {
    title: "Start a conversation",
    description: "Ask any financial question. Pick a focus mode to narrow the AI's expertise.",
    cta: "Open chat",
    href: "/chat",
    icon: MessageSquare,
    accent: "text-sky-500",
    minRole: "user",
  },
  {
    title: "Run intelligence analysis",
    description: "Multi-model AI + government data to surface portfolio risks and opportunities.",
    cta: "Go to Intelligence",
    href: "/intelligence-hub",
    icon: Brain,
    accent: "text-purple-500",
    minRole: "user",
  },
  {
    title: "Open Engine Dashboard",
    description: "UWE + BIE + HE projections, Monte Carlo, stress tests, strategy comparison.",
    cta: "Launch engines",
    href: "/engine-dashboard",
    icon: Calculator,
    accent: "text-amber-500",
    minRole: "user",
  },
  {
    title: "Continue learning",
    description: "Flashcards, practice questions, and certification tracks (SIE, Series 7, CFP).",
    cta: "Study a track",
    href: "/learning",
    icon: GraduationCap,
    accent: "text-emerald-500",
    minRole: "user",
  },
  {
    title: "Review leads",
    description: "Kanban pipeline across 7 stages. Click a lead to see full context.",
    cta: "Open pipeline",
    href: "/leads",
    icon: Users,
    accent: "text-rose-500",
    minRole: "advisor",
  },
  {
    title: "Advisory Hub",
    description: "Product catalog, case management, and AI-powered suitability recommendations.",
    cta: "Browse products",
    href: "/advisory",
    icon: Sparkles,
    accent: "text-violet-500",
    minRole: "advisor",
  },
];

function canSee(userRole: string, minRole: string): boolean {
  const order = ["user", "advisor", "manager", "admin"];
  return order.indexOf(userRole) >= order.indexOf(minRole);
}

// ─── Page ───────────────────────────────────────────────────────────────────

export default function Dashboard() {
  const { user, loading: authLoading } = useAuth();
  const role = (user as { role?: string } | null)?.role ?? "user";
  const displayName = (user as { name?: string; email?: string } | null)?.name
    ?? (user as { email?: string } | null)?.email?.split("@")[0];

  // Real tRPC queries — every one is against an existing procedure (verified
  // in Pass 82). `retry: false` so a transient error surfaces a skeleton
  // instead of blocking the whole page.
  const conversationsQ = trpc.conversations.list.useQuery(undefined, {
    enabled: !!user,
    retry: false,
  });
  // insights.list accepts `status: new | viewed | acted | dismissed | snoozed`.
  // We want "not yet dismissed" — the procedure already filters out
  // dismissed when no status is passed (see server/routers/insights.ts:30),
  // so we leave status undefined and limit to 5.
  const insightsQ = trpc.insights.list.useQuery(
    { limit: 5 },
    { enabled: !!user, retry: false },
  );
  const insightStatsQ = trpc.insights.stats.useQuery(undefined, {
    enabled: !!user,
    retry: false,
  });
  const masteryQ = trpc.learning.mastery.summary.useQuery(undefined, {
    enabled: !!user,
    retry: false,
  });

  const conversations = conversationsQ.data ?? [];
  const insights = insightsQ.data ?? [];
  const insightStats = insightStatsQ.data;
  const mastery = masteryQ.data;

  const visibleActions = QUICK_ACTIONS.filter((a) => canSee(role, a.minRole));

  if (authLoading) {
    return (
      <AppShell>
        <main id="main-content" className="flex items-center justify-center h-64">
          <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
        </main>
      </AppShell>
    );
  }

  return (
    <AppShell title="Dashboard">
      <main id="main-content" className="container mx-auto max-w-6xl px-4 py-6 md:py-8 space-y-6 md:space-y-8">
        {/* ── 1. Welcome header ─────────────────────────────────────── */}
        <header className="space-y-3">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <h1 className="text-2xl md:text-3xl font-semibold tracking-tight">
                {greeting(displayName)}
              </h1>
              <p className="text-sm text-muted-foreground mt-0.5">
                Your financial command center — pick up where you left off or try something new.
              </p>
            </div>
            <Badge variant="outline" className="capitalize text-xs">
              {role} account
            </Badge>
          </div>

          {/* Compact stat strip — each tile has a loading + empty fallback. */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            <StatTile
              label="Conversations"
              value={conversationsQ.isLoading ? "—" : String(conversations.length)}
              loading={conversationsQ.isLoading}
              icon={MessageSquare}
            />
            <StatTile
              label="New insights"
              value={insightStatsQ.isLoading ? "—" : String(insightStats?.newCount ?? 0)}
              loading={insightStatsQ.isLoading}
              icon={Sparkles}
            />
            <StatTile
              label="Mastery"
              value={
                masteryQ.isLoading
                  ? "—"
                  : mastery?.masteryPct != null
                    ? `${mastery.masteryPct}%`
                    : "0%"
              }
              loading={masteryQ.isLoading}
              icon={GraduationCap}
            />
            <StatTile
              label="Due today"
              value={masteryQ.isLoading ? "—" : String(mastery?.dueNow ?? 0)}
              loading={masteryQ.isLoading}
              icon={Activity}
            />
          </div>
        </header>

        {/* ── 2. Quick actions ──────────────────────────────────────── */}
        <section aria-labelledby="quick-actions-heading" className="space-y-3">
          <h2 id="quick-actions-heading" className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Quick actions
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {visibleActions.map((action) => {
              const Icon = action.icon;
              return (
                <Link key={action.href} href={action.href}>
                  <a className="group block">
                    <Card className="h-full transition-all hover:border-accent/40 hover:shadow-md cursor-pointer">
                      <CardContent className="p-5 space-y-3">
                        <div className="flex items-center justify-between">
                          <Icon className={`h-6 w-6 ${action.accent}`} />
                          <ArrowRight className="h-4 w-4 text-muted-foreground/40 group-hover:text-accent group-hover:translate-x-0.5 transition-all" />
                        </div>
                        <div>
                          <p className="font-semibold text-[15px]">{action.title}</p>
                          <p className="text-xs text-muted-foreground mt-1 leading-relaxed line-clamp-2">
                            {action.description}
                          </p>
                        </div>
                        <p className="text-xs text-accent font-medium">{action.cta} →</p>
                      </CardContent>
                    </Card>
                  </a>
                </Link>
              );
            })}
          </div>
        </section>

        {/* ── 3. Recent activity ────────────────────────────────────── */}
        <section aria-labelledby="activity-heading" className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {/* Conversations */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <MessageSquare className="h-4 w-4 text-sky-500" />
                Recent conversations
              </CardTitle>
              <CardDescription className="text-xs">
                Pick up where you left off.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {conversationsQ.isLoading ? (
                <SkeletonList rows={3} />
              ) : conversations.length === 0 ? (
                <EmptyRow
                  text="No conversations yet."
                  cta={{ label: "Start your first chat", href: "/chat" }}
                />
              ) : (
                conversations.slice(0, 3).map((conv: { id: number; title?: string | null; updatedAt?: string | number | Date | null }) => (
                  <Link key={conv.id} href={`/chat/${conv.id}`}>
                    <a className="flex items-center justify-between gap-3 p-2 rounded-md hover:bg-secondary/50 transition-colors group">
                      <span className="text-sm truncate">{conv.title ?? "Untitled"}</span>
                      <span className="text-[11px] text-muted-foreground shrink-0">
                        {timeAgo(conv.updatedAt ?? null)}
                      </span>
                    </a>
                  </Link>
                ))
              )}
              {conversations.length > 3 && (
                <Link href="/chat">
                  <a className="block text-xs text-accent hover:underline pt-1">
                    View all {conversations.length} conversations →
                  </a>
                </Link>
              )}
            </CardContent>
          </Card>

          {/* Proactive insights */}
          <Card>
            <CardHeader className="pb-3">
              <CardTitle className="text-base flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-purple-500" />
                AI insights for you
              </CardTitle>
              <CardDescription className="text-xs">
                Patterns the AI noticed across your data.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-2">
              {insightsQ.isLoading ? (
                <SkeletonList rows={3} />
              ) : insights.length === 0 ? (
                <EmptyRow
                  text="No active insights yet."
                  cta={{ label: "Run analysis", href: "/intelligence-hub" }}
                />
              ) : (
                insights.slice(0, 3).map((insight: { id: number; title?: string | null; category?: string | null; priority?: string | null; suggestedAction?: string | null }) => (
                  <div
                    key={insight.id}
                    className="p-3 rounded-md border border-border/50 bg-secondary/20 space-y-1"
                  >
                    <div className="flex items-start justify-between gap-2">
                      <p className="text-sm font-medium truncate">{insight.title ?? "Insight"}</p>
                      {insight.priority && (
                        <Badge
                          variant="outline"
                          className={
                            insight.priority === "critical" || insight.priority === "high"
                              ? "text-[10px] border-rose-500/40 text-rose-500"
                              : "text-[10px]"
                          }
                        >
                          {insight.priority}
                        </Badge>
                      )}
                    </div>
                    {insight.suggestedAction && (
                      <p className="text-[11px] text-muted-foreground line-clamp-2">
                        {insight.suggestedAction}
                      </p>
                    )}
                  </div>
                ))
              )}
            </CardContent>
          </Card>
        </section>

        {/* ── 4. Feature spotlight (static for now) ─────────────────── */}
        <section aria-labelledby="spotlight-heading" className="space-y-3">
          <h2 id="spotlight-heading" className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
            Try this next
          </h2>
          <Card className="bg-gradient-to-br from-accent/5 to-transparent border-accent/20">
            <CardContent className="p-5 flex items-start gap-4">
              <TrendingUp className="h-8 w-8 text-accent shrink-0 mt-1" />
              <div className="flex-1 space-y-2">
                <p className="font-semibold">Multi-model consensus analysis</p>
                <p className="text-xs text-muted-foreground leading-relaxed max-w-xl">
                  Ask one question, get answers from 3-5 different AI models (Claude, GPT, Gemini, and more) simultaneously. See where they agree, where they disagree, and get a synthesized answer with agreement scoring — ideal for high-stakes financial decisions.
                </p>
                <Link href="/consensus">
                  <Button size="sm" variant="outline" className="mt-1">
                    Open Consensus page →
                  </Button>
                </Link>
              </div>
            </CardContent>
          </Card>
        </section>
      </main>
    </AppShell>
  );
}

// ─── Small presentational helpers ──────────────────────────────────────────

function StatTile({
  label,
  value,
  loading,
  icon: Icon,
}: {
  label: string;
  value: string;
  loading?: boolean;
  icon: LucideIcon;
}) {
  return (
    <div className="rounded-lg border border-border/60 bg-card/40 p-3 flex items-center gap-3">
      <Icon className="h-4 w-4 text-muted-foreground shrink-0" />
      <div className="min-w-0">
        <p className="text-[10px] text-muted-foreground uppercase tracking-wider truncate">
          {label}
        </p>
        {loading ? (
          <div className="h-5 w-8 bg-secondary/50 rounded animate-pulse mt-0.5" />
        ) : (
          <p className="text-lg font-semibold tabular-nums leading-tight">{value}</p>
        )}
      </div>
    </div>
  );
}

function SkeletonList({ rows }: { rows: number }) {
  return (
    <div className="space-y-2">
      {Array.from({ length: rows }).map((_, i) => (
        <div key={i} className="h-10 bg-secondary/30 rounded-md animate-pulse" />
      ))}
    </div>
  );
}

function EmptyRow({
  text,
  cta,
}: {
  text: string;
  cta?: { label: string; href: string };
}) {
  return (
    <div className="text-center py-4 space-y-2">
      <p className="text-xs text-muted-foreground">{text}</p>
      {cta && (
        <Link href={cta.href}>
          <a className="inline-block text-xs text-accent hover:underline font-medium">
            {cta.label} →
          </a>
        </Link>
      )}
    </div>
  );
}
