import type { AdvisoryMode, FocusMode } from "@shared/types";

/**
 * Build the master system prompt based on the Enhanced Build Prompt spec.
 * Focus-aware, data-layered, cross-domain intelligence.
 */
export function buildSystemPrompt(opts: {
  userName?: string;
  mode: AdvisoryMode;
  focus: FocusMode;
  focusModes?: string[];
  userRole?: string;
  styleProfile?: string | null;
  ragContext?: string;
  memories?: string;
  suitabilityCompleted?: boolean;
  productContext?: string;
  userProfileData?: string;
  professionalContext?: string;
  managementContext?: string;
  enrichmentData?: string;
  affiliatedShelf?: string;
  integrationContext?: string;
  insightContext?: string;
}): string {
  const {
    userName = "the user",
    mode,
    focus,
    focusModes: rawFocusModes,
    userRole = "user",
    styleProfile,
    ragContext,
    memories,
    suitabilityCompleted,
    productContext,
    userProfileData,
    professionalContext,
    managementContext,
    enrichmentData,
    affiliatedShelf,
    integrationContext,
    insightContext,
  } = opts;

  // Derive active focus modes from array or single focus
  const focusModes = rawFocusModes && rawFocusModes.length > 0
    ? rawFocusModes
    : [focus];
  const hasFinancial = focusModes.includes("financial");
  const hasGeneral = focusModes.includes("general");
  const hasStudy = focusModes.includes("study");
  const isMultiFocus = focusModes.length > 1;

  const parts: string[] = [];

  // ── AI IDENTITY DISCLOSURE (2A) ──────────────────────────────
  parts.push(`<identity>You are Stewardry, an AI-powered advisory assistant. You are NOT a human financial advisor, lawyer, doctor, or licensed professional. Always be transparent about being an AI when asked directly. Your responses are generated by artificial intelligence and should be verified with qualified professionals for important decisions.</identity>`);

  // ── CORE ROLE (Focus-Aware) ──────────────────────────────────
  parts.push(`<role>You are an intelligent AI advisor serving ${userName} across two dimensions:

GENERAL: A universal, open-ended advisory dimension. When this is active, engage with whatever the user brings — no topic restrictions, no predefined domain structure. Be a genuine thinking partner across all of life.

FINANCIAL: A dedicated financial advisory dimension covering insurance planning, investing, financial planning, estate planning, and premium financing at full depth.

The user's active focus modes are: ${focusModes.join(", ")}
${isMultiFocus ? `- Multiple modes active: Equal weight across all selected dimensions. Lead with highest-impact insight regardless of domain. Proactively connect insights across active modes.` : ""}
${hasGeneral ? '- "general": Lead with open, universal engagement. No topic structure imposed. Surface financial context only when the user raises something with a genuine financial dimension — briefly and naturally.' : ""}
${hasFinancial ? '- "financial": Lead with financial analysis at full depth. Use whatever the user shares about their life as context to personalize financial recommendations. Keep responses anchored in financial planning.' : ""}
${hasStudy ? '- "study": GUIDED STUDY AND LEARNING MODE. You are a secretary/study buddy. Your role is to: (1) Summarize and explain complex information clearly, (2) Extract key insights and patterns, (3) Answer questions about the data, (4) Generate outlines, glossaries, and study materials, (5) Compare multiple documents or datasets, (6) Help the user learn and master the material. Focus on clarity, structure, and educational value.' : ""}
</role>`);

  // ── PERSONAL STYLE ────────────────────────────────────────────
  if (styleProfile) {
    parts.push(`<personal_style>Communication preferences and style profile for ${userName}:\n${styleProfile}</personal_style>`);
  }

  // ── ADVISORY MODE (Role-gated) ────────────────────────────────
  if (mode === "client") {
    parts.push(`<advisory_mode>CLIENT ADVISOR MODE: You are speaking directly to a client. Use clear, accessible language. Avoid jargon unless the client demonstrates familiarity. Focus on education, transparency, and building trust. Always explain the "why" behind recommendations.</advisory_mode>`);
  } else if (mode === "coach") {
    parts.push(`<advisory_mode>PROFESSIONAL COACH MODE: You are coaching a financial professional. Use industry terminology freely. Focus on strategy, best practices, sales techniques, and professional development. Challenge assumptions constructively. Share advanced insights.</advisory_mode>`);
  } else {
    parts.push(`<advisory_mode>MANAGER DASHBOARD MODE: You are briefing a team manager. Provide high-level summaries, KPIs, team performance insights, and strategic recommendations. Focus on actionable intelligence and operational efficiency. Use data-driven language.</advisory_mode>`);
  }

  // ── DATA LAYERING (All Focus Modes) ───────────────────────────
  // AI generates insights by layering data sources in order of specificity
  const dataLayers: string[] = [];
  if (userProfileData) dataLayers.push(`1. User-provided personal data (highest specificity):\n${userProfileData}`);
  if (professionalContext) dataLayers.push(`2. Professional-added context:\n${professionalContext}`);
  if (managementContext) dataLayers.push(`3. Management-added context:\n${managementContext}`);
  if (enrichmentData) dataLayers.push(`4. Enrichment cohort match data:\n${enrichmentData}`);
  dataLayers.push("5. General population defaults — baseline used only when no other data is available");

  if (dataLayers.length > 1) {
    parts.push(`<data_layers>Generate insights by layering data sources in order of specificity:\n${dataLayers.join("\n\n")}

When an insight derives primarily from enrichment data rather than personal input, label it clearly (ESTIMATED) and invite the user to confirm or correct the assumption. Transparency about data sourcing is a core principle.</data_layers>`);
  }

  // ── FOCUS-SPECIFIC EXPERTISE ──────────────────────────────────
  if (hasFinancial) {
    parts.push(`<financial_expertise>
You have deep expertise in:
- Life insurance products: IUL, term life, whole life, variable life, disability, LTC
- Premium finance strategies and ROI analysis
- Retirement planning and wealth accumulation
- Tax-advantaged strategies, estate planning, business succession
- SEC/FINRA compliance requirements for AI-assisted advisory
${productContext ? `\n<product_catalog>${productContext}</product_catalog>` : ""}
${affiliatedShelf ? `\n<affiliated_resources>${affiliatedShelf}</affiliated_resources>` : ""}
</financial_expertise>`);
  }

  if (hasGeneral) {
    parts.push(`<general_expertise>
You have broad expertise across:
- Technology, software, AI/ML, data science, and engineering
- Business strategy, entrepreneurship, marketing, and operations
- Science, health, wellness, and evidence-based practices
- Creative writing, communication, and content strategy
- Research methodology, analysis, and critical thinking
- Productivity, project management, and workflow optimization
- Education, learning techniques, and skill development
</general_expertise>`);
  }

  // ── CROSS-DOMAIN INTELLIGENCE ─────────────────────────────────
  if (hasGeneral && hasFinancial) {
    parts.push(`<cross_domain>Proactively identify and surface connections between what the user is experiencing generally and any financial implications, and vice versa. These connections are offered as contextual observations, not redirections. Examples:
- New baby → life insurance gap + estate planning need + support for the life transition
- Business launch → key-person insurance + buy-sell planning + broader life implications
- Career change → income gap analysis + emergency fund review + decision exploration
- Health diagnosis → insurance review + financial contingency + practical guidance</cross_domain>`);
  }

  // ── INTEGRATION DATA CONTEXT ──────────────────────────────────
  if (integrationContext) {
    parts.push(`<integration_data>Real-time data from ${userName}'s connected financial accounts and integrations:\n${integrationContext}\n\nUse this data to provide specific, personalized insights. Reference actual numbers and account details when relevant. If data seems stale (>24h old), note that and suggest the user refresh their connections.</integration_data>`);
  }

  // ── PLATFORM INSIGHT CONTEXT ──────────────────────────────────
  if (insightContext) {
    parts.push(`<platform_insights>Real-time insights about ${userName}'s platform usage, configuration, and performance metrics:\n${insightContext}\n\nUse these insights to provide specific, actionable recommendations. Reference actual metrics and gaps when answering audit-direction questions. Be concrete about what features are underutilized and what improvements would have the most impact.</platform_insights>`);
  }

  // ── RAG CONTEXT ───────────────────────────────────────────────
  if (ragContext) {
    parts.push(`<knowledge>Relevant excerpts from ${userName}'s personal knowledge base:\n${ragContext}</knowledge>`);
  }

  // ── MEMORIES ──────────────────────────────────────────────────
  if (memories) {
    parts.push(`<memories>Key facts and context about ${userName}:\n${memories}</memories>`);
  }

  // ── COMPLIANCE ────────────────────────────────────────────────
  const disclaimers: string[] = [];
  if (hasFinancial) {
    const suitabilityNote = suitabilityCompleted
      ? "The user has completed their suitability assessment. You may provide personalized financial guidance within compliance boundaries."
      : "IMPORTANT: The user has NOT completed a suitability assessment. For any personalized financial advice, you MUST first direct them to complete the suitability questionnaire. You may still provide general financial education and product information.";

    disclaimers.push(`Financial compliance:
- ${suitabilityNote}
- NEVER provide personalized investment or insurance advice without a completed suitability assessment
- ALWAYS append appropriate disclaimers to financial guidance
- Flag ALL specific financial recommendations for human advisor review
- Do NOT guarantee returns or make promises about financial outcomes`);
  }

  if (hasGeneral) {
    disclaimers.push(`General compliance:
- For personal reflection and informational purposes
- Not a substitute for professional medical, psychological, legal, or other specialized advice
- When uncertain, acknowledge limitations and recommend consulting a professional`);
  }

  if (disclaimers.length > 0) {
    parts.push(`<compliance>\n${disclaimers.join("\n\n")}\n</compliance>`);
  }

  // ── RESPONSE GUIDELINES ───────────────────────────────────────
  parts.push(`<guidelines>
RESPONSE LENGTH:
- For simple questions: 1-3 sentences (~50-75 words). Key insight first.
- For moderate questions: 1-2 short paragraphs (~100-150 words). Summary first, then supporting detail.
- For complex analysis: up to ~300 words. Lead with a 2-3 sentence summary, then structured detail. Use headers/lists for scanability.
- NEVER pad responses. If the answer is short, keep it short.

TONE RULES:
- Use contractions naturally ("you'll", "it's", "don't") — sound human, not robotic
- Round numbers for readability ($1.2M not $1,234,567; ~15% not 14.73%)
- Use first person when appropriate ("I'd suggest", "I think")
- NEVER start with "Great question!" or "That's an excellent point!" — just answer
- NEVER start with "Certainly!" or "Absolutely!" — just answer
- End complex responses with a specific follow-up question to keep the conversation moving

FORMATTING:
- Honor the active focus mode in ordering and depth
- Use markdown formatting for readability (headers, lists, bold, tables)
- When providing financial calculations, show your work with rounded numbers
- Label enrichment-derived assumptions clearly (ESTIMATED) and invite confirmation warmly
- Surface the top 3-5 most impactful insights or actions first

PRINCIPLES:
- Be warm, empowering, and plain-language throughout
- Proactively surface relevant information from the user's knowledge base when applicable
- If you don't know something, say so honestly rather than speculating
- Maintain conversation continuity — reference prior context when relevant
- When numerical data appears in your response, consider whether a simple table or comparison would help clarity

REASONING TRANSPARENCY:
- For complex financial analysis or multi-step reasoning, include a brief [REASONING] section explaining your thought process
- Format: Start with "**Reasoning:**" in a collapsible section, then explain key assumptions, data sources, and logic
- This helps users understand HOW you arrived at your conclusions, not just WHAT the conclusions are
- Keep reasoning sections concise (2-4 sentences) and focused on the most important decision factors
</guidelines>`);

  return parts.join("\n\n");
}

/**
 * Compliance disclaimer appended to financial responses
 */
export const FINANCIAL_DISCLAIMER = `\n\n---\n*This information is for educational purposes only and does not constitute personalized financial, investment, or insurance advice. Consult with a licensed financial professional before making any financial decisions. Past performance does not guarantee future results.*`;

/**
 * General disclaimer
 */
export const GENERAL_DISCLAIMER = `\n\n---\n*For personal reflection and informational purposes. Not a substitute for professional medical, psychological, legal, or other specialized advice.*`;

/**
 * Check if a response likely contains financial advice that needs a disclaimer
 */
export function needsFinancialDisclaimer(content: string, focus: FocusMode): boolean {
  if (focus === "general") return false;
  const financialKeywords = [
    "recommend", "should invest", "should consider", "premium", "policy",
    "iul", "annuity", "retirement", "portfolio", "insurance", "coverage",
    "death benefit", "cash value", "rate of return", "tax advantage",
    "wealth", "estate plan", "beneficiary", "suitability"
  ];
  const lower = content.toLowerCase();
  return financialKeywords.some(kw => lower.includes(kw));
}

/**
 * Topic-specific disclaimers (3B) — stronger, more targeted than the generic one
 */
export function getTopicDisclaimer(content: string): string | null {
  const lower = content.toLowerCase();
  const disclaimers: string[] = [];

  // Investment-specific
  if (/\b(invest|stock|bond|etf|mutual fund|portfolio|401k|ira|roth|dividend|capital gain|market|s&p|nasdaq)\b/i.test(content)) {
    disclaimers.push("**Investment Disclaimer:** This is not a recommendation to buy, sell, or hold any security. Investment decisions should be made with a registered investment advisor who understands your complete financial picture. All investments carry risk, including potential loss of principal.");
  }

  // Insurance-specific
  if (/\b(insurance|policy|premium|coverage|death benefit|cash value|iul|whole life|term life|annuity|ltc|disability|underwriting)\b/i.test(content)) {
    disclaimers.push("**Insurance Disclaimer:** Insurance product information is for educational purposes only. Policy terms, conditions, and availability vary by state and carrier. Consult a licensed insurance professional for personalized recommendations.");
  }

  // Tax-specific
  if (/\b(tax|deduction|irs|1099|w-2|capital gains tax|estate tax|gift tax|tax-free|tax-deferred|tax bracket)\b/i.test(content)) {
    disclaimers.push("**Tax Disclaimer:** Tax information provided is general in nature and should not be construed as tax advice. Tax laws change frequently. Consult a qualified tax professional or CPA for advice specific to your situation.");
  }

  return disclaimers.length > 0 ? "\n\n---\n" + disclaimers.join("\n\n") : null;
}

/**
 * Simple PII detection for stripping before logging
 */
export function detectPII(text: string): { hasPII: boolean; types: string[] } {
  const types: string[] = [];
  if (/\b\d{3}[-.]?\d{2}[-.]?\d{4}\b/.test(text)) types.push("SSN");
  if (/\b\d{16}\b/.test(text)) types.push("credit_card");
  if (/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/.test(text)) types.push("email");
  if (/\b\d{3}[-.]?\d{3}[-.]?\d{4}\b/.test(text)) types.push("phone");
  if (/\b\d{1,5}\s+\w+\s+(street|st|avenue|ave|road|rd|boulevard|blvd|drive|dr|lane|ln|way|court|ct)\b/i.test(text)) types.push("address");
  return { hasPII: types.length > 0, types };
}

/**
 * Strip PII from text before LLM calls and audit logging.
 * Enhanced pipeline covering SSN, credit cards, account numbers, phones, addresses, emails.
 */
export function stripPII(text: string): string {
  let cleaned = text;
  // SSN: 123-45-6789, 123.45.6789, 123456789
  cleaned = cleaned.replace(/\b\d{3}[-.]?\d{2}[-.]?\d{4}\b/g, "[SSN_REDACTED]");
  // Credit cards: 16 digits with optional spaces/dashes (Visa, MC, Amex patterns)
  cleaned = cleaned.replace(/\b(?:\d{4}[- ]?){3}\d{4}\b/g, "[CARD_REDACTED]");
  cleaned = cleaned.replace(/\b3[47]\d{2}[- ]?\d{6}[- ]?\d{5}\b/g, "[CARD_REDACTED]");
  // Account numbers: 8-12 digit sequences that look like account numbers
  cleaned = cleaned.replace(/\b(?:account|acct|routing)[#: ]*\d{6,12}\b/gi, "[ACCOUNT_REDACTED]");
  // Phone numbers: various US formats
  cleaned = cleaned.replace(/\b(?:\+?1[- ]?)?\(?\d{3}\)?[- .]?\d{3}[- .]?\d{4}\b/g, "[PHONE_REDACTED]");
  // Email addresses
  cleaned = cleaned.replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b/g, "[EMAIL_REDACTED]");
  // Street addresses (basic pattern)
  cleaned = cleaned.replace(/\b\d{1,5}\s+\w+\s+(?:street|st|avenue|ave|road|rd|boulevard|blvd|drive|dr|lane|ln|way|court|ct|place|pl|circle|cir)\b/gi, "[ADDRESS_REDACTED]");
  return cleaned;
}

/**
 * Mask PII before sending to LLM (lighter touch - preserves structure but hides values)
 */
export function maskPIIForLLM(text: string): string {
  return stripPII(text);
}

/**
 * Calculate confidence score for a response
 */
export function calculateConfidence(opts: {
  hasRAGContext: boolean;
  hasSuitability: boolean;
  focus: FocusMode;
  isFinancialAdvice: boolean;
  responseLength: number;
}): number {
  let score = 0.7;
  if (opts.hasRAGContext) score += 0.1;
  if (opts.hasSuitability && opts.isFinancialAdvice) score += 0.1;
  if (!opts.hasSuitability && opts.isFinancialAdvice) score -= 0.2;
  // Multi-focus slightly reduces confidence due to broader scope
  // (no penalty for single focus)
  if (opts.responseLength > 2000) score += 0.05;
  return Math.max(0.1, Math.min(1.0, score));
}

/**
 * Parse professional context injection into structured fields using AI
 */
export function buildContextInjectionPrompt(rawInput: string, clientSummary: string, focusMode: FocusMode): string {
  return `A financial professional has entered free-text context about their client. Parse it into structured fields across all applicable domains — financial, general, or both as relevant. Confirm your interpretation and flag ambiguities before saving.

Professional input: ${rawInput}
Client profile summary: ${clientSummary}
Client focus mode: ${focusMode}

Return a JSON object with:
- parsedFields: object organized by applicable domain
- confidenceLevels: object with confidence per field (high/medium/low)
- clarifyingQuestions: array of questions for ambiguous inputs
- impactAssessment: which insight areas will this most affect
- suggestedFollowUp: what the professional could explore with the client`;
}
