/**
 * Task #40 — AI Badge + Watermark Service
 * Provenance tracking, content attribution, and AI-generated content marking
 */

export interface AIContentMetadata {
  generatedAt: string;
  modelUsed: string;
  confidenceScore: number;
  humanReviewed: boolean;
  reviewedBy?: string;
  reviewedAt?: string;
  contentHash: string;
  version: number;
  disclaimers: string[];
}

export function generateContentHash(content: string): string {
  let hash = 0;
  for (let i = 0; i < content.length; i++) {
    const char = content.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return Math.abs(hash).toString(36);
}

export function createAIBadge(content: string, opts?: {
  modelUsed?: string; confidenceScore?: number; humanReviewed?: boolean;
  reviewedBy?: string; disclaimers?: string[];
}): AIContentMetadata {
  return {
    generatedAt: new Date().toISOString(),
    modelUsed: opts?.modelUsed ?? "stewardly-ai",
    confidenceScore: opts?.confidenceScore ?? 0.85,
    humanReviewed: opts?.humanReviewed ?? false,
    reviewedBy: opts?.reviewedBy,
    reviewedAt: opts?.humanReviewed ? new Date().toISOString() : undefined,
    contentHash: generateContentHash(content),
    version: 1,
    disclaimers: opts?.disclaimers ?? [
      "This content was generated by AI and may contain inaccuracies.",
      "Not a substitute for professional financial advice.",
    ],
  };
}

export function markAsReviewed(metadata: AIContentMetadata, reviewerName: string): AIContentMetadata {
  return {
    ...metadata,
    humanReviewed: true,
    reviewedBy: reviewerName,
    reviewedAt: new Date().toISOString(),
  };
}

export function getWatermarkText(metadata: AIContentMetadata): string {
  const parts = [`AI-Generated | ${metadata.generatedAt}`];
  if (metadata.humanReviewed) {
    parts.push(`Reviewed by ${metadata.reviewedBy} on ${metadata.reviewedAt}`);
  }
  parts.push(`Confidence: ${Math.round(metadata.confidenceScore * 100)}%`);
  return parts.join(" | ");
}

export function validateContentIntegrity(content: string, metadata: AIContentMetadata): boolean {
  return generateContentHash(content) === metadata.contentHash;
}

/** Generate HTML badge for embedding in reports/exports */
export function generateHTMLBadge(metadata: AIContentMetadata): string {
  const color = metadata.humanReviewed ? "#22c55e" : "#f59e0b";
  const label = metadata.humanReviewed ? "AI + Human Reviewed" : "AI Generated";
  return `<span style="display:inline-flex;align-items:center;gap:4px;padding:2px 8px;border-radius:4px;background:${color}20;color:${color};font-size:12px;font-weight:500;border:1px solid ${color}40"><svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><circle cx="12" cy="12" r="10"/></svg>${label}</span>`;
}
